[package]
edition = "2018"
name = "parto"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cliffy = {git = "https://github.com/AminMoazzen/cliffy"}
image = "0.23.14"
